name: test
on: [push]

jobs:
  structurizr-cli:
    runs-on: ubuntu-latest
    name: Run structurizr-cli
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build an image
        id: build
        run: |
          IMAGE=test/structurizr-cli-action:${GITHUB_SHA}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"

      - name: CVE scan image
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: |
            --cache-dir /var/lib/trivy
            --no-progress
            --exit-code 1
            --severity MEDIUM,HIGH,CRITICAL
            ${{ steps.build.outputs.image }}

      - name: Run structurizr-cli action
        uses: ./
        id: test
        with:
          id: ${{ secrets.STZR_ID }}
          key: ${{ secrets.STZR_API_KEY }}
          secret: ${{ secrets.STZR_API_SECRET }}
          workspace: ./tests/workspace.dsl
