name: test
on: [push]

jobs:
  structurizr-cli:
    runs-on: ubuntu-latest
    name: Run structurizr-cli
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run structurizr-cli action
        uses: ./
        id: test
        with:
          id: ${{ secrets.STRUCTURIZR_CLOUD_WORKSPACE_ID }}
          key: ${{ secrets.STRUCTURIZR_CLOUD_KEY }}
          secret: ${{ secrets.STRUCTURIZR_CLOUD_SECRET }}
          workspace: ./tests/workspace.dsl
          url: https://api.structurizr.com
          merge: false
          archive: false
